name: ubuntu
on:
  push:
  pull_request:

jobs:
  build_aarch64_softmmu_linux:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - name: Install build dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build libsdl1.2-dev libexpat1-dev libssl-dev build-essential

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build qemu
        run: |
          mkdir build
          cd build
          ../configure --enable-sdl --enable-skinning --target-list=arm-softmmu
          make -j$(nproc)
      - name: Install qemu
        run: |
          cd build
          make DESTDIR=$GITHUB_WORKSPACE/bin/ install
      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: qemu-s5l89xx
          path: ${{ github.workspace }}/bin/
